### ISSUE TITLE
How can I use libs in desktop?

### ISSUE THREAD

**Issue by silloy** [jgraph/drawio-libs#7]
How can I use libs in desktop?

**Comment by alderg** [comment]
Click on File, Open Library.

**Comment by gutierrezps** [comment]
I built a library for draw.io with several icon files (200+). Instead of creating a single XML file, I grouped the icons in different categories and generated one XML file for each category (19 files total). Right now, File > Open Library only supports opening one library at a time.

Is there a way to import multiple library files at once? If not, should I open an issue in the [main repository](https://github.com/jgraph/drawio) to address this requirement?
